### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by wildwestrom** [yosevu/shadow-static#8]
Am I allowed to use, distribute, and modify the source code from your project in mine?
If so, what limitations?

Please consider making it copyleft to whatever extent you can. (Some of the libraries are incompatible with the GPL.)
https://www.gnu.org/licenses/#AGPL

**Comment by yosevu** [comment]
Thanks @wildwestrom. Much delayed since I missed this issue, but added the license in case someone else wants to use the code.

**Comment by wildwestrom** [comment]
It's too bad I'm not doing much CLJS these days, but better late than never.
Thank you :)
